name: Build PR
on: pull_request
jobs:
  lint:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Prettier check
        run: yarn prettier --check "./**/*.{js,md}"
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
